[project]
name = "personal-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "requests>=2.32.3",
    "ruff>=0.9.10",
    "werkzeug>=3.1.3",
]
